---
- name: Create /etc/profile.d/proxy.sh
  ansible.builtin.template:
    src: "proxy.sh.j2"
    dest: "/etc/profile.d/proxy.sh"
    owner: root
    group: root
    mode: '0755'

- name: Create /etc/apt/apt.conf.d/80proxy
  ansible.builtin.template:
    src: "80proxy.j2"
    dest: /etc/apt/apt.conf.d/80proxy
    owner: root
    group: root
    mode: '0644'
